<?php
$data = array (
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => '夹克/大衣',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '65',
    'name' => '夹克/大衣',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => '大衣',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '68',
    'name' => '大衣',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '马甲',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '69',
    'name' => '马甲',
  ),
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => '夹克',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '66',
    'name' => '夹克',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => '休闲外套',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '67',
    'name' => '休闲外套',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '牛仔裤',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '81',
    'name' => '牛仔裤',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => '马裤',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '84',
    'name' => '马裤',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '紧身裤',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '85',
    'name' => '紧身裤',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => '牛仔裤',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '82',
    'name' => '牛仔裤',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '牛仔短裤',
    'measure_unit' => '',
    'parent_id' => '81',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '83',
    'name' => '牛仔短裤',
  ),
  62 => 
  array (
    'cat_id' => '62',
    'cat_name' => '衬衫/罩衫',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '62',
    'name' => '衬衫/罩衫',
  ),
  64 => 
  array (
    'cat_id' => '64',
    'cat_name' => '罩衫',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '64',
    'name' => '罩衫',
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => '衬衫',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '63',
    'name' => '衬衫',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => '裤装',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '78',
    'name' => '裤装',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => '短裤',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '80',
    'name' => '短裤',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '其它',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '0',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '89',
    'name' => '其它',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '长裤',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '79',
    'name' => '长裤',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => '半身裙',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => '3',
    'level' => 0,
    'id' => '75',
    'name' => '半身裙',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '牛仔短裙',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '77',
    'name' => '牛仔短裙',
  ),
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => '半身裙',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '76',
    'name' => '半身裙',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => '连衣裙',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => '8',
    'level' => 0,
    'id' => '72',
    'name' => '连衣裙',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '休闲裙',
    'measure_unit' => '',
    'parent_id' => '72',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '74',
    'name' => '休闲裙',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => '连衣裙',
    'measure_unit' => '',
    'parent_id' => '72',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '73',
    'name' => '连衣裙',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => '沙滩装',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '109',
    'name' => '沙滩装',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '沙滩装',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '111',
    'name' => '沙滩装',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => '配饰',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '112',
    'name' => '配饰',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '泳衣',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '110',
    'name' => '泳衣',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => '首饰',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '103',
    'name' => '首饰',
  ),
  107 => 
  array (
    'cat_id' => '107',
    'cat_name' => '项链',
    'measure_unit' => '',
    'parent_id' => '103',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '107',
    'name' => '项链',
  ),
  104 => 
  array (
    'cat_id' => '104',
    'cat_name' => '手镯/手链',
    'measure_unit' => '',
    'parent_id' => '103',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '104',
    'name' => '手镯/手链',
  ),
  108 => 
  array (
    'cat_id' => '108',
    'cat_name' => '其它',
    'measure_unit' => '',
    'parent_id' => '103',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '108',
    'name' => '其它',
  ),
  105 => 
  array (
    'cat_id' => '105',
    'cat_name' => '戒指',
    'measure_unit' => '',
    'parent_id' => '103',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '105',
    'name' => '戒指',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => '耳环',
    'measure_unit' => '',
    'parent_id' => '103',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '106',
    'name' => '耳环',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => '上衣',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '57',
    'name' => '上衣',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => '简约Ｔ恤',
    'measure_unit' => '',
    'parent_id' => '57',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '61',
    'name' => '简约Ｔ恤',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => '印花Ｔ恤',
    'measure_unit' => '',
    'parent_id' => '57',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '58',
    'name' => '印花Ｔ恤',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => '针织衫',
    'measure_unit' => '',
    'parent_id' => '57',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '59',
    'name' => '针织衫',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => '无袖衫',
    'measure_unit' => '',
    'parent_id' => '57',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '60',
    'name' => '无袖衫',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => '开襟衫',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '70',
    'name' => '开襟衫',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '开襟衫',
    'measure_unit' => '',
    'parent_id' => '70',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '71',
    'name' => '开襟衫',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '裤袜',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '86',
    'name' => '裤袜',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '纯色裤袜',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '87',
    'name' => '纯色裤袜',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => '花纹裤袜',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '88',
    'name' => '花纹裤袜',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => '配饰',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '94',
    'name' => '配饰',
  ),
  101 => 
  array (
    'cat_id' => '101',
    'cat_name' => '皮带/腰带',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '101',
    'name' => '皮带/腰带',
  ),
  98 => 
  array (
    'cat_id' => '98',
    'cat_name' => '头饰',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '98',
    'name' => '头饰',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => '鞋',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '95',
    'name' => '鞋',
  ),
  102 => 
  array (
    'cat_id' => '102',
    'cat_name' => '其它',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '102',
    'name' => '其它',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '眼镜',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '99',
    'name' => '眼镜',
  ),
  96 => 
  array (
    'cat_id' => '96',
    'cat_name' => '假发',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '96',
    'name' => '假发',
  ),
  100 => 
  array (
    'cat_id' => '100',
    'cat_name' => '帽子',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '100',
    'name' => '帽子',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => '围巾',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '97',
    'name' => '围巾',
  ),
);
?>